name: Update Eligibility Requirements

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama service
        run: |
          ollama serve > /tmp/ollama.log 2>&1 &
          sleep 15
          ollama pull gemma3:1b
          nohup ollama serve > /tmp/ollama.log 2>&1 &

      - name: Setup credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run updater
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
