name: Update Eligibility Requirements For Rental Assistance Sheet

on:
  schedule:
    - cron: '0 1 1 * *'    # runs at 1 AM UTC on the 1st of every month
  workflow_dispatch:      # manual trigger

permissions:
  contents: write

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Cache Ollama model
        uses: actions/cache@v3
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama-model-${{ hashFiles('**/action.yml') }}
          restore-keys: |
            ${{ runner.os }}-ollama-model-

      - name: Install Ollama CLI
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Pull Ollama model (cached)
        run: ollama pull gemma3:4b

      - name: Start Ollama server and wait for readiness
        run: |
          ollama serve &> /dev/null &
          for i in {1..10}; do
            if ollama status; then
              echo "Ollama is ready"
              break
            fi
            echo "Waiting for Ollama… ($i/10)"
            sleep 3
          done

      - name: Create GCP credentials file
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run updater script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py

      - name: Commit and push updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d')"
          git push origin HEAD:main
