name: Update Eligibility Requirements For Rental Assistance Sheet

on:
  schedule:
    - cron: '0 1 1 * *'    # 1 AM UTC on the 1st of every month
  workflow_dispatch:      # manual trigger

permissions:
  contents: write

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | bash

      - name: Make scripts executable
        run: chmod +x run-llm.sh

      - name: Run LLM script
        run: ./run-llm.sh

      - name: Create credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Start Ollama service
        run: |
          ollama serve &
          sleep 10  # Wait for server to initialize
          ollama pull gemma3:4b

      - name: Run updater script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d')"
          git push origin HEAD:main
