name: Update Eligibility Requirements For Rental Assistance Sheet

on:
  schedule:
    - cron: '0 1 1 * *'  # 1 AM UTC every day (8 AM PT in summer, 7 AM PT in winter)
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # Explicitly grant write permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile


      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Run ollama
        run: |
          ollama serve &
          ollama pull gemma3:4b

      - name: Create credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run updater script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
        
      - name: Commit updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d')"
          
      - name: Push changes
        run: git push origin HEAD:main
