name: Update Eligibility Requirements

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Optimize memory
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "swapoff -a" >> $GITHUB_ENV  # Cleanup later

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libx11-6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxtst6

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-autoinstaller gspread langchain-ollama beautifulsoup4 selenium tiktoken

      - name: Start Ollama service
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          nohup ollama serve > /tmp/ollama.log 2>&1 &
          sleep 30
          ollama pull gemma3:4b
          curl -I http://localhost:11434

      - name: Setup credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Run updater
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          # Set Chrome options
          export CHROME_OPTS="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage"
          python main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ollama-logs
          path: /tmp/ollama.log

      - name: Cleanup
        run: |
          killall ollama || true
          sudo swapoff /swapfile
          sudo rm /swapfile
